services:
  db-server:
    image: mysql:8.4
    # コンテナ名を明示的に指定する
    container_name: go_app-db-container
    # ホスト名を明示的に指定する
    hostname: db-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_app
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
      TZ: 'Asia/Tokyo'

    # 起動時のコマンド
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # ディレクトリ同期。設定ファイルとMySQLのデータが保存される場所を同期している。コンテナは基本的に起動時に変更されてもコンテナ自体が止まるとデータが消えてしまうため、保存しておきたいものはホストマシンと同期しておく必要がある。
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  web-server:
    # コンテナ名を明示的に指定する
    container_name: go_app-web-container
    # ホスト名を明示的に指定する
    hostname: web-server
    build: ./
    volumes:
      - ./home:/home/
      # # Nginxの設定ファイルをローカル側で編集した物を使用したい
      # - ./nginx.conf:/etc/nginx/nginx.conf
      # httpd.confをローカル側で編集した物を使用したい
      - ./httpd.conf:/etc/httpd/conf/httpd.conf
    ports:
      - "80:80"
      - "8080:8080"
